server:
  port: 8088
    # eureka
eureka:
   instance:
     hostname: localhost
   client:
     fetch-registry: false
     register-with-eureka: false
     service-url: # map key-value
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

